default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  username: postgres
  password: postgres
  host: localhost

test:
  <<: *default
  database: kora_ico_frontend_db_test

production:
  <<: *default
  database: kora_ico_frontend_db_production

development:
  <<: *default
  database: kora_ico_frontend_db_development