class CountryFlag
  def self.all
    [
        {title: "Portugal", code: "portugal"},
        {title: "Republic of the Congo", code: "republicofthe_congo"},
        {title: "Aruba", code: "aruba"},
        {title: "Macedonia", code: "macedonia"},
        {title: "Gibraltar", code: "gibraltar"},
        {title: "Croatia", code: "croatia"},
        {title: "Latvia", code: "latvia"},
        {title: "Djibouti", code: "djibouti"},
        {title: "Falkland Islands (Islas Malvinas)", code: "falkland_islands"},
        {title: "Austria", code: "austria"},
        {title: "British Indian Ocean Territory", code: "british_indian_ocean_territory"},
        {title: "Finland", code: "finland"},
        {title: "Bostswana", code: "bostswana"},
        {title: "Colombia", code: "colombia"},
        {title: "Norfolk Island", code: "norfolk_island"},
        {title: "Central African Republic", code: "central_african_republic"},
        {title: "Equatorial Guinea", code: "equatorial_guinea"},
        {title: "Timor Leste", code: "timor_leste"},
        {title: "Czech Republic", code: "czech_republic"},
        {title: "Antigua and Barbuda", code: "antiguaand_barbuda"},
        {title: "South Korea", code: "south_korea"},
        {title: "Bosnia and Herzegovina", code: "bosniaand_herzegovina"},
        {title: "India", code: "india"},
        {title: "China", code: "china"},
        {title: "Nauru", code: "nauru"},
        {title: "Bangladesh", code: "bangladesh"},
        {title: "Vanuatu", code: "vanuatu"},
        {title: "Iceland", code: "iceland"},
        {title: "Cambodia", code: "cambodia"},
        {title: "Taiwan", code: "taiwan"},
        {title: "Ghana", code: "ghana"},
        {title: "Barbados", code: "barbados"},
        {title: "Philippines", code: "philippines"},
        {title: "Chad", code: "chad"},
        {title: "Estonia", code: "estonia"},
        {title: "Eritrea", code: "eritrea"},
        {title: "Cote dIvoire", code: "coted_ivoire"},
        {title: "Ukraine", code: "ukraine"},
        {title: "Tamil Nation", code: "tamil_nation"},
        {title: "Hong Kong", code: "hong_kong"},
        {title: "Norway", code: "norway"},
        {title: "Oman", code: "oman"},
        {title: "Kyrgyzstan", code: "kyrgyzstan"},
        {title: "Syria", code: "syria"},
        {title: "Tuvalu", code: "tuvalu"},
        {title: "Guatemala", code: "guatemala"},
        {title: "Cape Verde", code: "cape_verde"},
        {title: "Sweden", code: "sweden"},
        {title: "Brunei", code: "brunei"},
        {title: "Lithuania", code: "lithuania"},
        {title: "Bahrain", code: "bahrain"},
        {title: "Hungary", code: "hungary"},
        {title: "Micronesia", code: "micronesia"},
        {title: "Bermuda", code: "bermuda"},
        {title: "Lesotho", code: "lesotho"},
        {title: "European Union", code: "european_union"},
        {title: "Romania", code: "romania"},
        {title: "Mali", code: "mali"},
        {title: "Mayotte", code: "mayotte"},
        {title: "Sri Lanka", code: "sri_lanka"},
        {title: "Cyprus", code: "cyprus"},
        {title: "Democratic Republic of the Congo", code: "democratic_republicofthe_congo"},
        {title: "Japan", code: "japan"},
        {title: "Moldavia", code: "moldavia"},
        {title: "Togo", code: "togo"},
        {title: "Brazil", code: "brazil"},
        {title: "Kenya", code: "kenya"},
        {title: "Belgium", code: "belgium"},
        {title: "Liberia", code: "liberia"},
        {title: "Montserrat", code: "montserrat"},
        {title: "Saudi Arabia", code: "saudi_arabia"},
        {title: "Wales", code: "wales"},
        {title: "Russia", code: "russia"},
        {title: "Ireland", code: "ireland"},
        {title: "Tunisia", code: "tunisia"},
        {title: "Kazahstan", code: "kazahstan"},
        {title: "Zambia", code: "zambia"},
        {title: "Egypt", code: "egypt"},
        {title: "Germany", code: "germany"},
        {title: "Ecuador", code: "ecuador"},
        {title: "Mongolia", code: "mongolia"},
        {title: "Saint Kitts and Nevis", code: "saint_kittsand_nevis"},
        {title: "Saint Pierre and Miquelon", code: "saint_pierreand_miquelon"},
        {title: "Palau", code: "palau"},
        {title: "Rwanda", code: "rwanda"},
        {title: "Thailand", code: "thailand"},
        {title: "Mauritius", code: "mauritius"},
        {title: "South Georgia and the South Sandwitch Islands", code: "south_georgiaandthe_south_sandwitch_islands"},
        {title: "Palestine", code: "palestine"},
        {title: "Cameroon", code: "cameroon"},
        {title: "Spain", code: "spain"},
        {title: "Canada", code: "canada"},
        {title: "the Gambia", code: "the_gambia"},
        {title: "Luxembourg", code: "luxembourg"},
        {title: "Pitcairn Islands", code: "pitcairn_islands"},
        {title: "Gabon", code: "gabon"},
        {title: "Saint Vincent", code: "saint_vincent"},
        {title: "the Bahamas", code: "the_bahamas"},
        {title: "Turkmenistan", code: "turkmenistan"},
        {title: "France", code: "france"},
        {title: "Afghanistan", code: "afghanistan"},
        {title: "New Zealand", code: "new_zealand"},
        {title: "Dominica", code: "dominica"},
        {title: "Poland", code: "poland"},
        {title: "Cuba", code: "cuba"},
        {title: "Mexico", code: "mexico"},
        {title: "Guernsey", code: "guernsey"},
        {title: "Montenegro", code: "montenegro"},
        {title: "Pakistan", code: "pakistan"},
        {title: "Mauritania", code: "mauritania"},
        {title: "Monaco", code: "monaco"},
        {title: "Virgin Islands", code: "virgin_islands"},
        {title: "Tanzania", code: "tanzania"},
        {title: "Tibet", code: "tibet"},
        {title: "Armenia", code: "armenia"},
        {title: "Netherlands", code: "netherlands"},
        {title: "Malta", code: "malta"},
        {title: "Niger", code: "niger"},
        {title: "Albania", code: "albania"},
        {title: "Paraguay", code: "paraguay"},
        {title: "Burma (Myanmar)", code: "burma"},
        {title: "Guyana", code: "guyana"},
        {title: "Iraq", code: "iraq"},
        {title: "Holy See (Vatican City)", code: "holy_see"},
        {title: "Libya", code: "libya"},
        {title: "El Salvador", code: "el_salvador"},
        {title: "Uzbekistan", code: "uzbekistan"},
        {title: "Tonga", code: "tonga"},
        {title: "Marschal Islands", code: "marschal_islands"},
        {title: "Netherlands Anthilles", code: "netherlands_anthilles"},
        {title: "Suriname", code: "suriname"},
        {title: "Sao Tome and Principe", code: "sao_tomeand_principe"},
        {title: "Chile", code: "chile"},
        {title: "Kuwait", code: "kuwait"},
        {title: "Georgia", code: "georgia"},
        {title: "Malaysia", code: "malaysia"},
        {title: "Zimbabwe", code: "zimbabwe"},
        {title: "Burkina Faso", code: "burkina_faso"},
        {title: "Madagascar", code: "madagascar"},
        {title: "Isle of Man", code: "isleof_man"},
        {title: "Puerto Rico", code: "puerto_rico"},
        {title: "South Africa", code: "south_africa"},
        {title: "Trinidad and Tobago", code: "trinidadand_tobago"},
        {title: "Belarus", code: "belarus"},
        {title: "Iran", code: "iran"},
        {title: "Comoros", code: "comoros"},
        {title: "Northern Mariana Islands", code: "northern_mariana_islands"},
        {title: "North Korea", code: "north_korea"},
        {title: "Jamaica", code: "jamaica"},
        {title: "Guam", code: "guam"},
        {title: "Somalia", code: "somalia"},
        {title: "Angola", code: "angola"},
        {title: "Vietnam", code: "vietnam"},
        {title: "Namibia", code: "namibia"},
        {title: "Saint Helena", code: "saint_helena"},
        {title: "Fiji", code: "fiji"},
        {title: "Bulgaria", code: "bulgaria"},
        {title: "Honduras", code: "honduras"},
        {title: "Andorra", code: "andorra"},
        {title: "Haiti", code: "haiti"},
        {title: "Kosovo", code: "kosovo"},
        {title: "Singapore", code: "singapore"},
        {title: "Malawi", code: "malawi"},
        {title: "French Poynesia", code: "french_poynesia"},
        {title: "Greenland", code: "greenland"},
        {title: "Cayman Islands", code: "cayman_islands"},
        {title: "Anguilla", code: "anguilla"},
        {title: "Panama", code: "panama"},
        {title: "Switzerland", code: "switzerland"},
        {title: "Laos", code: "laos"},
        {title: "Kurdistan Nation", code: "kurdistan_nation"},
        {title: "Azerbaijan", code: "azerbaijan"},
        {title: "American Samoa", code: "american_samoa"},
        {title: "Bolivia", code: "bolivia"},
        {title: "Senegal", code: "senegal"},
        {title: "Scotland", code: "scotland"},
        {title: "Indonesia", code: "indonesia"},
        {title: "Nepal", code: "nepal"},
        {title: "Uganda", code: "uganda"},
        {title: "Venezuela", code: "venezuela"},
        {title: "Sierra Leone", code: "sierra_leone"},
        {title: "Yemen", code: "yemen"},
        {title: "Jordan", code: "jordan"},
        {title: "Seychelles", code: "seychelles"},
        {title: "Benin", code: "benin"},
        {title: "Australia", code: "australia"},
        {title: "Turks and Caicos Islands", code: "turksand_caicos_islands"},
        {title: "Slovenia", code: "slovenia"},
        {title: "Lebanon", code: "lebanon"},
        {title: "Burundi", code: "burundi"},
        {title: "Slovakia", code: "slovakia"},
        {title: "Samoa", code: "samoa"},
        {title: "Israel", code: "israel"},
        {title: "Algeria", code: "algeria"},
        {title: "Guinea", code: "guinea"},
        {title: "Maldives", code: "maldives"},
        {title: "Mozambique", code: "mozambique"},
        {title: "Peru", code: "peru"},
        {title: "Costa Rica", code: "costa_rica"},
        {title: "Tajikistan", code: "tajikistan"},
        {title: "Macau", code: "macau"},
        {title: "Cook Islands", code: "cook_islands"},
        {title: "Swaziland", code: "swaziland"},
        {title: "Argentina", code: "argentina"},
        {title: "Guinea Blissau", code: "guinea_blissau"},
        {title: "Belize", code: "belize"},
        {title: "Italy", code: "italy"},
        {title: "Denmark", code: "denmark"},
        {title: "Ethiopia", code: "ethiopia"},
        {title: "Saint Lucia", code: "saint_lucia"},
        {title: "Wallis and Futuna", code: "wallisand_futuna"},
        {title: "Solomon Islands", code: "solomon_islands"},
        {title: "San Marino", code: "san_marino"},
        {title: "Sudan", code: "sudan"},
        {title: "Uruguay", code: "uruguay"},
        {title: "Turkey", code: "turkey"},
        {title: "Nicaragua", code: "nicaragua"},
        {title: "United States", code: "united_states"},
        {title: "United Kingdom", code: "united_kingdom"},
        {title: "Papua New Guinea", code: "papua_new_guinea"},
        {title: "Nigeria", code: "nigeria"},
        {title: "Morocco", code: "morocco"},
        {title: "Faroe Islands", code: "faroe_islands"},
        {title: "Quatar", code: "quatar"},
        {title: "Grenada", code: "grenada"},
        {title: "Liechtenstein", code: "liechtenstein"},
        {title: "Bouvet Island", code: "bouvet_island"},
        {title: "Dominican Republic", code: "dominican_republic"},
        {title: "Kiribati", code: "kiribati"},
        {title: "Serbia", code: "serbia"},
        {title: "United Arab Emirates", code: "united_arab_emirates"},
        {title: "England", code: "england"},
        {title: "Niue", code: "niue"},
        {title: "Christmas Islands", code: "christmas_islands"},
        {title: "Greece", code: "greece"},
        {title: "Cocos (Keeling) Islands", code: "cocos"},
        {title: "Bhutan", code: "bhutan"},
        {title: "British Virgin Islands", code: "british_virgin_islands"}
    ].sort{|a,b| a[:title] <=> b[:title]}
  end

  def self.find(code)
    all.select{|hash| hash[:code] == code }.try(:first)
  end
end